name       : libgphoto2
version    : 2.5.8
release    : 5
source     :
    - http://internode.dl.sourceforge.net/project/gphoto/libgphoto/2.5.8/libgphoto2-2.5.8.tar.bz2 : 031a262e342fae43f724afe66787947ce1fb483277dfe5a8cf1fbe92c58e27b6
license    : LGPL-2.0
component  : multimedia.library
emul32     : yes
summary    : Digital Camera access library
description: |
    Digital Camera access library
patterns   :
    - devel: [/usr/share/man/man3]
builddeps  :
    - pkgconfig(gdlib)
    - pkgconfig32(gdlib)
    - pkgconfig(libusb-1.0)
    - pkgconfig32(libusb-1.0)
    - pkgconfig(libexif)
    - pkgconfig32(libexif)
    - pkgconfig32(libxml-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
    - libtool-32bit-devel
rundeps    :
    - devel: libexif-devel
    - 32bit-devel: libexif-32bit-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
