name       : libgphoto2
version    : 2.5.7
release    : 1
source     :
    - http://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.7/libgphoto2-2.5.7.tar.bz2 : 7260193277bdb4c319dd8f151224f87deac9fde64cbe5d2eb25d9c19e4d09894
license    : LGPL-2.0
summary    : Digital Camera access library
description: |
    Digital Camera access library
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(libexif)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
