name       : libgphoto2
version    : 2.5.25
release    : 14
source     :
    - https://github.com/gphoto/libgphoto2/archive/v2.5.25.tar.gz : 34ddb868b166b531100b08606d7de970fe8d4aad42f3d5e02c646efdcfc5ef7e
license    : LGPL-2.1-or-later
component  : multimedia.library
emul32     : yes
summary    : Digital Camera access library
description: |
    libgphoto2 is a library that can be used by applications to access various digital cameras.
patterns   :
    - devel : [/usr/share/man/man3]
builddeps  :
    - pkgconfig32(gdlib)
    - pkgconfig32(libexif)
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(libxml-2.0)
    - libtool-32bit-devel
rundeps    :
    - devel : libexif-devel
    - 32bit-devel : libexif-32bit-devel
setup      : |
    autoreconf --install --symlink
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm -rf $installdir/%libdir%/udev
    else
        # Generate hardware rules
        export CAMLIBS=$installdir/%libdir%/$package/$version
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/usr/lib64
        $installdir/%libdir%/$package/print-camera-list udev-rules version 201 > $workdir/40-libgphoto2.rules
        $installdir/%libdir%/$package/print-camera-list hwdb > $workdir/20-gphoto.hwdb
        install -D -m 00644 $workdir/40-libgphoto2.rules $installdir/%libdir%/udev/rules.d/40-libgphoto2.rules
        install -D -m 00644 $workdir/20-gphoto.hwdb $installdir/%libdir%/udev/hwdb.d/20-gphoto.hwdb
    fi
check      : |
    %make check
