name       : libgphoto2
version    : 2.5.8
release    : 4
source     :
    - http://internode.dl.sourceforge.net/project/gphoto/libgphoto/2.5.8/libgphoto2-2.5.8.tar.bz2 : 031a262e342fae43f724afe66787947ce1fb483277dfe5a8cf1fbe92c58e27b6
license    : LGPL-2.0
summary    : Digital Camera access library
description: |
    Digital Camera access library
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(libexif)
    - pkgconfig(gdlib)
rundeps    :
    - devel: libexif-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
