name       : libgphoto2
version    : 2.5.16
release    : 7
source     :
    - https://kent.dl.sourceforge.net/project/gphoto/libgphoto/2.5.16/libgphoto2-2.5.16.tar.bz2 : e757416d1623e01a9d0d294b2e790162e434c0964f50d3b7ff1a3424b62a2906
license    : LGPL-2.1
component  : multimedia.library
emul32     : yes
summary    : Digital Camera access library
description: |
    Digital Camera access library
patterns   :
    - devel : [/usr/share/man/man3]
builddeps  :
    - pkgconfig32(gdlib)
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(libexif)
    - pkgconfig32(libxml-2.0)
    - libtool-32bit-devel
rundeps    :
    - devel : libexif-devel
    - 32bit-devel : libexif-32bit-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
