name       : libgphoto2
version    : 2.5.22
release    : 12
source     :
    - https://github.com/gphoto/libgphoto2/archive/libgphoto2-2_5_22-release.tar.gz : cc588d0f1f1bed7d4069c49252b84952d4172ad4b1a5e38a340da647e65c042a
license    : LGPL-2.1-or-later
component  : multimedia.library
emul32     : yes
summary    : Digital Camera access library
description: |
    libgphoto2 is a library that can be used by applications to access
    various digital cameras.
patterns   :
    - devel : [/usr/share/man/man3]
builddeps  :
    - pkgconfig32(gdlib)
    - pkgconfig32(libexif)
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(libxml-2.0)
    - libtool-32bit-devel
rundeps    :
    - devel : libexif-devel
    - 32bit-devel : libexif-32bit-devel
setup      : |
    autoreconf --install --symlink
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    # remove circular symlink
    rm $installdir/usr/include/gphoto2/gphoto2

    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm -rf $installdir/%libdir%/udev
    else
        # Generate hardware rules
        export CAMLIBS=$installdir/%libdir%/$package/$version
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/usr/lib64
        $installdir/%libdir%/$package/print-camera-list udev-rules version 201 > $workdir/40-libgphoto2.rules
        $installdir/%libdir%/$package/print-camera-list hwdb > $workdir/20-gphoto.hwdb
        install -D -m 00644 $workdir/40-libgphoto2.rules $installdir/%libdir%/udev/rules.d/40-libgphoto2.rules
        install -D -m 00644 $workdir/20-gphoto.hwdb $installdir/%libdir%/udev/hwdb.d/20-gphoto.hwdb
    fi
check      : |
    %make check
